//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.01 at 09:42:01 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3dchools.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.w3dchools;
